config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get 'help' => 'static_pages#help'
  get 'about' => 'static_pages#about'
  get 'contact' => 'static_pages#contact'

  resources :static_pages do
  	resources :province, :prefecture
  end
  resources :province
end

app/models/province.rb
class Province < ActiveRecord::Base
  belongs_to :prefecture
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/province_controller.rb
class ProvinceController < ApplicationController
	def show
		@provinces = Province.all
	end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
include ProvinceHelper

  def home
  	
  end

  def help
  end

  def about
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title = '')
    base_title = "Framgia E-learning"
    if page_title.empty?
      base_title
    else
      "#{page_title} | #{base_title}"
    end
  end
end

app/helpers/province_helper.rb
module ProvinceHelper
end

app/views/layouts/_footer.html.erb
<footer>
  <div class="col-md-6">
    <span>Design by <strong>Nguyen Duy Ta</strong>  @Copyright 2016</span>
  </div>
  <div class="col-md-6">
    <ul class="nav navbar-nav navbar-right">
      <li><%= link_to "Home", root_path %></li>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Help", help_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
    </ul>
  </div>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to 'Volunteer', root_path, id: 'logo' %>
  </div>
    <title><%= full_title yield(:title) %></title>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= stylesheet_link_tag    'top_design', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <%= render 'layouts/shim' %>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd">
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="ja" lang="ja" dir="ltr">
<%= render 'layouts/header' %>
<body class="jscScrollTop">

<div class="container content">
  <% flash.each do |message_type, message| %>
    <div class="text-center alert alert-<%= message_type %>"><%= message%></div>
  <% end %>
  <%= yield %>
</div>
<%= render 'province/index'%>

<%= render 'layouts/footer' %>
</body>
</html>

app/views/province/_index.html.erb
<div class="headerWrap">
<div class="headerKv" style="background: grey;"></div>
      <div class="areaSelectWrap">
        <h2 class="areaSelectTitle">都道府県からおNPOを探す</h2>
        <ul class="areaSelectList">
          <li>
            <dl>
              <dt>北海道・東北</dt>
              <% for pro in @provinces%>
                <% if pro.prefecture_id == 1 %>
                  <dd><a href="<%= pro.id %>"><%= pro.name%></a></dd>
                <% end %>
              <%end%>
            </dl>
          </li>
          <li>
            <dl>
              <dt>関東</dt>
              <% for pro in @provinces%>
                <% if pro.prefecture_id == 2 %>
                  <dd><a href="<%= pro.id %>"><%= pro.name%></a></dd>
                <% end %>
              <%end%>
            </dl>
          </li>
          <li>
            <dl>
              <dt>北陸・甲信越</dt>
              <% for pro in @provinces%>
                <% if pro.prefecture_id == 3 %>
                  <dd><a href="<%= pro.id %>"><%= pro.name%></a></dd>
                <% end %>
              <%end%>
            </dl>
          </li>
          <li>
            <dl>
              <dt>中部</dt>
              <% for pro in @provinces%>
                <% if pro.prefecture_id == 4 %>
                  <dd><a href="<%= pro.id %>"><%= pro.name%></a></dd>
                <% end %>
              <%end%>
            </dl>
          </li>
          <li>
            <dl>
              <dt>関西</dt>
              <% for pro in @provinces%>
                <% if pro.prefecture_id == 5 %>
                  <dd><a href="<%= pro.id %>"><%= pro.name%></a></dd>
                <% end %>
              <%end%>
            </dl>
          </li>
          <li>
            <dl>
              <dt>中国</dt>
              <% for pro in @provinces%>
                <% if pro.prefecture_id == 6 %>
                  <dd><a href="<%= pro.id %>"><%= pro.name%></a></dd>
                <% end %>
              <%end%>
            </dl>
          </li>
          <li>
            <dl>
              <dt>四国</dt>
              <% for pro in @provinces%>
                <% if pro.prefecture_id == 7 %>
                  <dd><a href="<%= pro.id %>"><%= pro.name%></a></dd>
                <% end %>
              <%end%>
            </dl>
          </li>
          <li>
            <dl>
              <dt>九州・沖縄</dt>
              <% for pro in @provinces%>
                <% if pro.prefecture_id == 8 %>
                  <dd><a href="<%= pro.id %>"><%= pro.name%></a></dd>
                <% end %>
              <%end%>
            </dl>
          </li>
        </ul>
      </div>
</div>

app/views/static_pages/about.html.erb
<% provide :title, 'About' %>
<h1>What about me?</h1>

app/views/static_pages/contact.html.erb
<% provide :title, 'Contact' %>
<h1>Call me baby</h1>
<h2><a href="tel:1-888-888-8888"> 09696969696</a></h2>

app/views/static_pages/help.html.erb
<% provide :title, 'Help' %>
<h1>Help Page</h1>

app/views/static_pages/home.html.erb
<% provide :title, 'Home' %>